name: NPM Publish

on:
  push:
    branches:
      - version/node-16

jobs:
  publish_node_16:
    name: Publish with Node.js 16
    if: github.ref == 'refs/heads/version/node-16'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: version/node-16

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: 'Bump Version'
      - run: |
          npm version prerelease --force

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Package
        run: |
          npm run build
