name: NPM Publish

on:
  push:
    branches:
      - main
      - version/node-16

jobs:
  publish_node_16:
    name: Publish with Node.js 16
    if: github.ref == 'refs/heads/version/node-16' # Only run on version/node-16 branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: version/node-16 # Checkout the specific branch

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: 'Bump Version'
      - run: |
          npm version patch

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Package
        run: |
          npm run build
