// MESSAGES
export const SEND_NEW_MESSAGE = 'SEND_NEW_MESSAGE';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const DELETE_NEW_MESSAGE = 'DELETE_NEW_MESSAGE';
export const REACT_TO_LAST_MESSAGE = 'REACT_TO_LAST_MESSAGE';
export const SHOW_AGENT_FORM = 'SHOW_AGENT_FORM';
export const ADD_REPLY = 'ADD_REPLY';

// UI
export const SET_QUICK_REPLIES = 'SET_QUICK_REPLIES';
export const CLEAR_QUICK_REPLIES = 'CLEAR_QUICK_REPLIES';
export const EXPAND_WIDGET = 'EXPAND_WIDGET';
export const MINIMIZE_WIDGET = 'MINIMIZE_WIDGET';
export const SET_WIDGET_CONFIG = 'SET_WIDGET_CONFIG';

// BOT
export const DECRYPT_BOT = 'DECRYPT_BOT';

// USER
export const SET_VISITOR_ID = 'SET_VISITOR_ID';