// MESSAGES
export const SEND_NEW_MESSAGE = 'SEND_NEW_MESSAGE';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const DELETE_NEW_MESSAGE = 'DELETE_NEW_MESSAGE';
export const REACT_TO_LAST_MESSAGE = 'REACT_TO_LAST_MESSAGE';
export const SHOW_AGENT_FORM = 'SHOW_AGENT_FORM';
export const ADD_REPLY = 'ADD_REPLY';
export const ADD_ERROR_REPLY = 'ADD_ERROR_REPLY';
export const CLEAR_CHAT_MESSAGES = 'CLEAR_CHAT_MESSAGES';

// AGENT_HANDOVER
export const SHOW_AGENT_HANDOVER_FORM = 'SHOW_AGENT_HANDOVER_FORM';
export const SUBMIT_AGENT_HANDOVER_FORM = 'SUBMIT_AGENT_HANDOVER_FORM';
export const CANCEL_AGENT_HANDOVER = 'CANCEL_AGENT_HANDOVER';

// UI
export const SET_QUICK_REPLIES = 'SET_QUICK_REPLIES';
export const CLEAR_QUICK_REPLIES = 'CLEAR_QUICK_REPLIES';
export const EXPAND_WIDGET = 'EXPAND_WIDGET';
export const MINIMIZE_WIDGET = 'MINIMIZE_WIDGET';
export const SET_WIDGET_CONFIG = 'SET_WIDGET_CONFIG';
export const ADD_REACTION_TO_LAST_MESSAGE = 'ADD_REACTION_TO_LAST_MESSAGE';
export const SHOW_NEW_MESSAGE_BADGE = 'SHOW_NEW_MESSAGE_BADGE';
export const CLEAR_NEW_MESSAGE_BADGE = 'CLEAR_NEW_MESSAGE_BADGE';
export const START_TYPING_MESSAGE = 'START_TYPING_MESSAGE';
export const STOP_TYPING_MESSAGE = 'STOP_TYPING_MESSAGE';
export const SET_WIDGET_TO_FULL_HEIGHT = 'SET_WIDGET_TO_FULL_HEIGHT';
export const RESTORE_WIDGET_HEIGHT = 'RESTORE_WIDGET_HEIGHT';
export const SET_WIDGET_TO_FULLSCREEN = 'SET_WIDGET_TO_FULLSCREEN';
export const SET_WIDGET_WIDTH_TO_HALF_FULLSCREEN = 'SET_WIDGET_WIDTH_TO_HALF_FULLSCREEN';
export const RESTORE_WIDGET_WIDTH = 'RESTORE_WIDGET_WIDTH';

// BOT
export const DECRYPT_BOT = 'DECRYPT_BOT';

// USER
export const SET_VISITOR_ID = 'SET_VISITOR_ID';

// WEBSOCKET
export const DISCONNECT_WEBSOCKET = 'DISCONNECT_WEBSOCKET';
export const SET_WS_CHANNEL = 'SET_WS_CHANNEL';
export const SET_WS_ASK_QUESTION_ACTION = 'SET_WS_ASK_QUESTION_ACTION';
